### ISSUE TITLE
Hi , bro .Can i train my own dataset with your pretrained model?

### ISSUE THREAD

**Issue by qhdqhd** [tding1/CDFI#10]
thanks.
Because i have  a little dataset ,and I want to speed up training.

**Comment by tding1** [comment]
Yes. Please cite our work wherever possible.

**Comment by qhdqhd** [comment]
Of course my friend

**Comment by qhdqhd** [comment]
@tding1 
Another question my friend, all image resolution in Vimeo-90k Dataset is 448X256 ，can i try higher resolution dataset like 2K without change your code? Or  448X256 is enough good?
Thanks.

**Comment by qhdqhd** [comment]
@tding1

**Comment by tding1** [comment]
Yes, go ahead.
