### ISSUE TITLE
Testing result on vimeo90k_septuplet

### ISSUE THREAD

**Issue by silence-moon** [tding1/CDFI#12]
Hello, my friend! I tested the model with pretrained model 'FLAVR_4x.pth' (yours) and dataset 'vimeo90k_septuplet', and the result of psnr I had got was 28.376122. I don't konw why it occurs.
![image](https://user-images.githubusercontent.com/48373941/120947205-8914b680-c771-11eb-8435-26afed0ed8da.png)

**Comment by tding1** [comment]
'FLAVR_4x.pth' is not our model. Are you submitting the wrong issue?

**Comment by silence-moon** [comment]
Sorry,Sorry.
