### ISSUE TITLE
Train problem

### ISSUE THREAD

**Issue by qhdqhd** [tding1/CDFI#13]
Hi，my friend.
I use your pretrained `CDFI_adacof.pth`  ,and train on my own dataset (5fps video, larger movement object ,about 10000 triple data,same format as vimeo_triplet)

Training from 88 epoch (your pretrained model)  to 150 epoch , cost  a few days on my 1080Ti.

Your pretrained model is not too bad on my dataset
But after training I got very Little improvement. 
Here is my log.
[log.txt](https://github.com/tding1/CDFI/files/6636499/log.txt)
 

Can you tell me why?

**Comment by tding1** [comment]
You are saying that you start with our pre-trained model, but why in your log the very first evaluation results on Middebury are so bad? See the average below:

Average:       24.5427584428654662 0.7672963823557910     0.0548322839507212

**Comment by qhdqhd** [comment]
> You are saying that you start with our pre-trained model, but why in your log the very first evaluation results on Middebury are so bad? See the average below:
> 
> Average: 24.5427584428654662 0.7672963823557910 0.0548322839507212

sorry I did not  explain well. I change both vimeo_triplet and Middebury .
I change Middebury  using my own data (large movement) .Using raw data is meanless,  right?

**Comment by qhdqhd** [comment]
![im1](https://user-images.githubusercontent.com/42370719/121793434-73036c00-cc31-11eb-9b40-94b4c137545d.png)
![im2](https://user-images.githubusercontent.com/42370719/121793436-7991e380-cc31-11eb-80be-dcbe07d86b54.png)
![im3](https://user-images.githubusercontent.com/42370719/121793437-7c8cd400-cc31-11eb-96e9-c34e66f46296.png)
Here is one triple in my dataset ,Thank you.

**Comment by qhdqhd** [comment]
@tding1  My friend ,do you have any idea about this ? Thank you !

**Comment by llmpass** [comment]
Before  I can answer this question, could you tell us more details of your training? 
Did you
1) retrain our model from scratch with your own dataset? or
2) retrain our model from our checkpoint  with your own dataset? or
3) retrain original Adacof from scratch with your own dataset, then compress the model and add additional parts as described in our paper?

**Comment by qhdqhd** [comment]
My friend .I use your pretrained model (maybe 88 epochs ) and use my own dataset (same format as vimeo_triplet , about 10000 images triple )  
Train from 88 epoch to 300 epoch .The result improve a little . Average PSNR improve 2dB.

**Comment by qhdqhd** [comment]
@llmpass

**Comment by llmpass** [comment]
> My friend .I use your pretrained model (maybe 88 epochs ) and use my own dataset (same format as vimeo_triplet , about 10000 images triple )
> Train from 88 epoch to 300 epoch .The result improve a little . Average PSNR improve 2dB.

2db is a lot!

Why don't you follow the path of 

retrain original Adacof from scratch with your own dataset, then compress the model and add additional parts as described in our paper.

Since features are data dependent, so that the pruning is also data dependent.

**Comment by qhdqhd** [comment]
Thank you my friend .
