### ISSUE TITLE
Different  result in the same test data with different resolution? Why?

### ISSUE THREAD

**Issue by qhdqhd** [tding1/CDFI#19]
hello, my friend.
I trained model based on my own data (same format as Vimeo-90K,  448X256 resolution).
When I test my model, I found different  result in the same test data with different resolution.
Data with 1280X720 resolution is a little bad while the same data with 448X256 is better.
Here is the result.

**Comment by qhdqhd** [comment]
As shown in the figure, differences are mainly blue light in the distance(large motion) and some local details.
@tding1

**Comment by qhdqhd** [comment]
Anyone can answer my question?
Thank you!

**Comment by tding1** [comment]
Your training data has resolution 448X256, so probably you would obtain better results for this resolution.

**Comment by qhdqhd** [comment]
I feel confused...  The public dataset like  Vimeo-90K is also 448X256.  @Does it face the same problem?

**Comment by tding1** [comment]
The results reported are both trained and tested on the same resolution. It might not perform as expected if your model is trained on one resolution but is tested on another resolution.
