### ISSUE TITLE
inconsistent SSIM computation

### ISSUE THREAD

**Issue by sniklaus** [tding1/CDFI#2]
I was surprised to see that the ratio between PSNR and SSIM deviates between the methods with dagger and the ones without dagger in Table 3, by a large margin. I noticed that the provided `test.py` uses the following.

https://github.com/tding1/CDFI/blob/d7f79e502674187b7a7b645a7812fd9fa30a6608/test.py#L46-L47

In doing so, it does not provide a `data_range` argument and `skimage.metrics.structural_similarity` has to guess it. However, it just uses the [difference between the smallest and the largest element](https://github.com/scikit-image/scikit-image/blob/a69d49272145d9839df75f3ee398c0bbde32f448/skimage/metrics/_structural_similarity.py#L164) as a fallback. This significantly alters the results and puts the methods with dagger in Table 3 at a substantial disadvantage though (and half of the methods have a dagger).

I just updated the `test.py` as follows (which also addresses the quantization issue from #1).

```
...

gt = (gt * 255).round() / 255
frame_out = (frame_out * 255).round() / 255

psnr = skimage.metrics.peak_signal_noise_ratio(image_true=gt, image_test=frame_out)
ssim = skimage.metrics.structural_similarity(np.transpose(gt, (1, 2, 0)),
                                             np.transpose(frame_out, (1, 2, 0)), data_range=1.0, multichannel=True)

...
```

With this fix, the SSIM of CDFI on the Middlebury test drops from 0.983 to 0.966 which is quite significant. It would hence be great if Table 3 could get revised such that future work that references it is not subject to the same inconsistencies. Thanks!

**Comment by tding1** [comment]
Thanks for pointing this question! I will take time to investigate this issue and revise the arxiv version of the paper if possible.

**Comment by tding1** [comment]
I have updated the quantitative results. The new table looks like the following:
![29361616895253_ pic_hd](https://user-images.githubusercontent.com/30458935/112739733-adb80b00-8f44-11eb-8646-e2a04b3c5488.jpg)
A new arXiv version of the paper should appear soon, and the official CVPR paper is also revised accordingly (so they will be consistent).

Thanks again for pointing out this issue!

**Comment by sniklaus** [comment]
Thank you for updating/revising this!
