### ISSUE TITLE
cupy and CUDA compatibility 

### ISSUE THREAD

**Issue by sramakintel** [tding1/CDFI#20]
what is the pip3 command for installing cupy ?

For CUDA 11.0 
the command should be pip3 install cupy-cuda110

but cupy version 7.7.0(from README) is not compatible with cupy-cuda110 

pip3 install cupy-cuda110==7.7.0 gives errors..

the only command works is pip3 install cupy-cuda100==7.7.0 but that refers to cuda 10.0. Very confusing. can you help clarify?

**Comment by tding1** [comment]
You may want to try 

conda install -c conda-forge cupy cudatoolkit=11.0

**Comment by sramakintel** [comment]
It works. Thanks :)
