### ISSUE TITLE
How to determine the number of channels in a compressed model?

### ISSUE THREAD

**Issue by zdyshine** [tding1/CDFI#23]
Hi, Bro. Thank you for your open source. I got the density according to the steps in **Apply CDFI to New Models**. But how to determine the number of channels of the compressed model according to the density? Can you share how to do it? Thank you!

**Comment by llmpass** [comment]
Suppose for a particular layer, you got 70% sparsity (30% density), 64 channels in and 64 channels out, then the target number of channels will be 64 * sqrt(0.7) = 53 roughly.

**Comment by zdyshine** [comment]
> Suppose for a particular layer, you got 70% sparsity (30% density), 64 channels in and 64 channels out, then the target number of channels will be 64 * sqrt(0.7) = 53 roughly.

Thanks. The whole process I understand is that finetune gets the density, and then manually designs the number of network layers according to the density. Is that right?

**Comment by llmpass** [comment]
exactly!
