### ISSUE TITLE
About pruning layer problems.

### ISSUE THREAD

**Issue by cocowy1** [tding1/CDFI#24]
Congratuations!  This work is so helpful to me, but I am still confused how to prune these channles in detail, could you release the codes about pruning?

**Comment by tding1** [comment]
In short, we use density of each layer as the compression ratio of that layer. For example, if a conv layer has size 100 x 100 x 3 x 3, and the density is 0.81 (after running the L1 optimizer), then after pruning we reconstruct it as 90 x 90 x 3 x 3. Just a reminder that there is no golden rule of how to prune the channels, you can also come up with your own idea of prune a specific layer based on the density level. FYI, we are currently working on a journal version of the paper which would include more details on how to prune the model with computed sparsity. Hopefully this will be released soon :)

**Comment by cocowy1** [comment]
Thx! And if the density ratio dl is samll,  would the number of channles in that layer become zero?

**Comment by tding1** [comment]
If the density ratio is really small, you can also consider removing that layer in the new reconstruction.
