### ISSUE TITLE
About the training time

### ISSUE THREAD

**Issue by mmSir** [tding1/CDFI#4]
your work is impressive! What kind of GPU have you trained on for a total of how many hours?

**Comment by tding1** [comment]
We train our model on RTX 6000 Ti GPU with batch size 8 for 100 epochs, which takes around several days. If you have limited resources, you may want to use a small batch size, or do a random crop on the training images (as provided [here](https://github.com/tding1/CDFI/blob/15f8b14fd9d71be978eae34ece2917c6aa5eb4ef/datasets.py#L40-L44)).

**Comment by mmSir** [comment]
thank for your replay!
