### ISSUE TITLE
Train on low rate video (5-10fps)? 

### ISSUE THREAD

**Issue by qhdqhd** [tding1/CDFI#9]
I find your model behave bad on low rate video (5-10fps), I wonder how to fix this? Maybe Train on low rate videos can help? Thanks a lot.

**Comment by qhdqhd** [comment]
I want to convert a 10FPS video to 30Fps

**Comment by tding1** [comment]
The behavior of a video interpolation model does not necessarily relate to the frame rate of the video. For example, the drifting demo video of this repo, which is 160FPS, is interpolated from a video of 5FPS, which performs very well. What actually matters is the content of the video, namely the motion of the objects, the occlusion among different objects, etc. If two input frames contain very complex movements of the underlying objects, an interpolation method may not perform as well as expected, which is exactly the difficulty of this research area.

**Comment by qhdqhd** [comment]
you are right ,the low rate video can be move slowly or largely. 
The low rate video with large moving  is hard to handle, right?

**Comment by tding1** [comment]
Yes, it is correct.

**Comment by qhdqhd** [comment]
Thanks. I wnoder if I train on dataset with  large moving object  can make some difference? 
 Honstely I just want to use it rather than research video interplolation.

**Comment by llmpass** [comment]
@qhdqhd What are the resolutions of your videos? My suggestion is resize your video to relatively small resolutions (say 320x240) and then try this model.

**Comment by qhdqhd** [comment]
> @qhdqhd你视频的分辨率是多少？我的建议是将您的视频调整为相对较小的分辨率（例如 320x240），然后尝试此模型。

4K or 2K video. You mean low resolutions   video have better result?

**Comment by qhdqhd** [comment]
> @qhdqhd What are the resolutions of your videos? My suggestion is resize your video to relatively small resolutions (say 320x240) and then try this model.
The train datasets use 448X256 resolution picture ,why dont they use large resolution pictures? Because of limited GPU memory?

**Comment by llmpass** [comment]
> > @qhdqhd What are the resolutions of your videos? My suggestion is resize your video to relatively small resolutions (say 320x240) and then try this model.
> > The train datasets use 448X256 resolution picture ,why dont they use large resolution pictures? Because of limited GPU memory?

No. We also trained 2K/4K resolution model, it is also pretty good.

**Comment by qhdqhd** [comment]
Thx for your reply.
I download Vimeo-90K datasets,and I find they are 448X256.  So you mean you have other 2K /4K datasets?

**Comment by llmpass** [comment]
> Thx for your reply.
> I download Vimeo-90K datasets,and I find they are 448X256. So you mean you have other 2K /4K datasets?

https://media.xiph.org/video/derf/

You can retrain the model on this dataset, hope this helps.

**Comment by qhdqhd** [comment]
Thank you. @llmpass @tding1

**Comment by rsjjdesj** [comment]
Is there any 2K video dataset that can be used for training. Should it not be in same format as vimeo images.

**Comment by qhdqhd** [comment]
> Is there any 2K video dataset that can be used for training. Should it not be in same format as vimeo images.

I mean I can create dataset  with same format like Vimeo .

**Comment by qhdqhd** [comment]
> Is there any 2K video dataset that can be used for training. Should it not be in same format as vimeo images.

I mean I can create dataset  with same format like Vimeo .

**Comment by rsjjdesj** [comment]
> > Is there any 2K video dataset that can be used for training. Should it not be in same format as vimeo images.
> 
> I mean I can create dataset with same format like Vimeo .

It is not easy to create the datasets which lead to good training. Please share the dataset if you are successful in training with the new dataset.
